star:
  version: v1
  nodeid: topology.regions.novisad.grbavica.node3
  rtopic: topology.regions.novisad.grbavica.node3.> 
  stopic: syncTopic
  errtopic: erroTtopic
  flusher: 0.0.0.0:4222
  instrument:
    address: 0.0.0.0:4222
    stopic: collector
    collect: 15s
    location: logs/


  #topology.regions.>
